name: My First Github Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: running command in linux
      run: |
        echo "Hi Nikhil! How are you?"
        echo "Hi Nikhil!!!, How to do it"
        ls -lrth
        pwd
        date
        df -kh
