name: My First Github Actions
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - name: Build Stage
      run: |
        echo "*********Build Stage*********"
        echo "Hi Nikhil! How are you?"
        echo "Hi Nikhil!!!, How to do it"
        ls -lrth
        pwd
        date
        df -kh

  Test:
    runs-on: ubuntu-latest
    # needs: Build
    if: ${{ success() }}
    steps:
    - name: Test Stage
      run: |
        echo "*********Test Stage*********"
        echo "Hi Nikhil! How are you?"
        echo "Hi Nikhil!!!, How to do it"
        ls -lrth
        pwd
        date
        df -kh

  Deploy:
    runs-on: ubuntu-latest
    # needs: Test
    if: ${{ success() }}
    steps:
    - name: Deploy Stage
      run: |
        echo "*********Deploy Stage*********"
        echo "Hi Nikhil! How are you?"
        echo "Hi Nikhil!!!, How to do it"
        ls -lrth
        pwd
        date
        df -kh

  Artifact:
    runs-on: ubuntu-latest
    needs: Deploy
    if: ${{ success() }}
    steps:
    - name: Artifact Creation Stage
      run: |
        echo "*********Artifact Creation Stage*********"
        echo "Hi Nikhil! How are you?"
        echo "Hi Nikhil!!!, How to do it"
        ls -lrth
        pwd
        date
        df -kh